# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dpoly <- function(X, R, taus) {
    .Call(`_gbggm_dpoly`, X, R, taus)
}

euclidean <- function(x) {
    .Call(`_gbggm_euclidean`, x)
}

pcor <- function(R) {
    .Call(`_gbggm_pcor`, R)
}

corp <- function(Rho) {
    .Call(`_gbggm_corp`, Rho)
}

Modularity <- function(adjMatrix, community) {
    .Call(`_gbggm_Modularity`, adjMatrix, community)
}

